### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by GianlucaMancusi** [pengzhangzhi/Awesome-Mamba#1]
MambaByte: https://github.com/kyegomez/MambaByte
MambaMorph: https://github.com/Guo-Stone/MambaMorph
Vivim: https://github.com/scott-yjyang/Vivim
SegMamba: https://github.com/ge-xing/SegMamba

mamba.py: https://github.com/alxndrTL/mamba.py

**Comment by pengzhangzhi** [comment]
Thanks!!!!

**Comment by GianlucaMancusi** [comment]
Swin-UMamba https://github.com/JiarunLiu/Swin-UMamba
